# ----
# Site
title: Awesome Title
#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /favicon-32x32.png
description: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
author:
  name:
  email: your-email@domain.com
  twitter: # twitter username without the @ symbol

# -----
# Build

timezone: Etc/UTC

collections:
  projects:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty
markdown: kramdown
excerpt_separator: ""   # Workaround for https://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed/
permalink: /:title ## disables post output
#sass:
#    style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE