# ----
# Site
title: Awesome Title
#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /favicon-32x32.png
description: Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
author:
  name:
  email: your-email@domain.com
  twitter: # twitter username without the @ symbol

# -----
# Build

timezone: Etc/UTC

collections:
  projects:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty
markdown: kramdown

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
  -
    scope:
      path: "contact.html"
    values:
      full_width: true

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/r3dlin3/agency-jekyll-theme
  - title: linkedin
    url: http://linkedin.com
  - title: facebook
    url: http://facebook.com

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# jekyll-archives:
#   enabled:
#     - categories

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE